config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # list all tasks
  get '/tasks', to: 'tasks#index'

  # Create new task: one that shows a form
  # one that saves it on DB
  get 'tasks/new', to: 'tasks#new', as: :tasks_new
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :tasks_edit

  # read one task only
  get '/tasks/:id', to: 'tasks#show', as: :task

  # edit tasks: one to show the task
  # one to save it on DB
  patch 'tasks/:id', to: 'tasks#update'

  #destroy: find the task
  # one to save it on DB
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save

    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    @task.save

    redirect_to tasks_path(@task.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RalisTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- here we can add a bootstrap link -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1> Edit a task // mark as done </h1>

<%= form_for @task do |f| %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'title of your task'%>
  </div>

  <div>
    <%= f.label :details %>
    <%= f.text_field :details, placeholder: 'details of your task'%>
  </div>
  <div>
    <%= f.label :completed %>
    <%= f.check_box :completed, placeholder: 'Is it done?'%>
  </div>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1> All tasks: </h1>

<%= link_to 'Create a new task', tasks_new_path %>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task_path(task.id) do %>
        <%= task.title %>: <%= task.details %><%= task.completed ? "[X]" : "" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Add a new task</h1>

<%= form_for @task do |f| %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'title of your task'%>
  </div>

  <div>
    <%= f.label :details %>
    <%= f.text_field :details, placeholder: 'details of your task'%>
  </div>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1> <%= @task.title %></h1>

<p> <%= @task.details %> </p>
<p> <%= @task.completed %> </p>

<%= link_to 'Edit task', tasks_edit_path %>
<%= link_to 'Delete task', task_path(@task.id), method: delete %>